#!/bin/bash
if [ $# -ne 1 ]; then
    echo $0: usage: installscript-creator command
    exit 1
fi
name=$1
name2="--run"
if [[ $name == $name2 ]]; then
   cd /opt/installscript-creator/
   bash main.sh
